repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        types: [r, yaml, markdown]

  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.3.2.9021
    hooks:
    - id: no-debug-statement
    - id: roxygenize
      additional_dependencies:
        - jsonlite
        - duckdb
        - stringr
    - id: use-tidy-description
    # Pretty-print files with {styler} https://styler.r-lib.org/
    - id: style-files
    - id: no-browser-statement
    - id: no-debug-statement
    - id: parsable-R
    - id: readme-rmd-rendered
    - id: codemeta-description-updated
    # https://search.r-project.org/CRAN/refmans/spelling/html/spell_check_files.html
    - id: spell-check
      # Don't spell-check data files
      exclude: '^.+\.csv$'
    - id: deps-in-desc
    - id: lintr

ci:
  autofix_prs: true
  autofix_commit_msg: '[pre-commit.ci] Fixing issues with pre-commit'
  autoupdate_schedule: weekly
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit-autoupdate'
  skip: [] # Optionally list ids of hooks to skip on CI
